#pragma once

#include "HorseIR/Tree/Node.h"

#include "HorseIR/Tree/Program.h"
#include "HorseIR/Tree/Module.h"
#include "HorseIR/Tree/LibraryModule.h"
#include "HorseIR/Tree/ModuleContent.h"
#include "HorseIR/Tree/ImportDirective.h"
#include "HorseIR/Tree/GlobalDeclaration.h"
#include "HorseIR/Tree/FunctionDeclaration.h"
#include "HorseIR/Tree/BuiltinFunction.h"
#include "HorseIR/Tree/Function.h"
#include "HorseIR/Tree/VariableDeclaration.h"
#include "HorseIR/Tree/Parameter.h"

#include "HorseIR/Tree/Statements/Statement.h"
#include "HorseIR/Tree/Statements/DeclarationStatement.h"
#include "HorseIR/Tree/Statements/AssignStatement.h"
#include "HorseIR/Tree/Statements/ExpressionStatement.h"
#include "HorseIR/Tree/Statements/IfStatement.h"
#include "HorseIR/Tree/Statements/WhileStatement.h"
#include "HorseIR/Tree/Statements/RepeatStatement.h"
#include "HorseIR/Tree/Statements/BlockStatement.h"
#include "HorseIR/Tree/Statements/ReturnStatement.h"
#include "HorseIR/Tree/Statements/BreakStatement.h"
#include "HorseIR/Tree/Statements/ContinueStatement.h"

#include "HorseIR/Tree/Expressions/Expression.h"
#include "HorseIR/Tree/Expressions/CallExpression.h"
#include "HorseIR/Tree/Expressions/CastExpression.h"
#include "HorseIR/Tree/Expressions/Operand.h"
#include "HorseIR/Tree/Expressions/Identifier.h"

#include "HorseIR/Tree/Expressions/Literals/Literal.h"
#include "HorseIR/Tree/Expressions/Literals/VectorLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/BooleanLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/CharLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/IntLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/Int8Literal.h"
#include "HorseIR/Tree/Expressions/Literals/Int16Literal.h"
#include "HorseIR/Tree/Expressions/Literals/Int32Literal.h"
#include "HorseIR/Tree/Expressions/Literals/Int64Literal.h"
#include "HorseIR/Tree/Expressions/Literals/FloatLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/Float32Literal.h"
#include "HorseIR/Tree/Expressions/Literals/Float64Literal.h"
#include "HorseIR/Tree/Expressions/Literals/ComplexLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/StringLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/SymbolLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/DatetimeLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/MonthLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/DateLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/MinuteLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/SecondLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/TimeLiteral.h"
#include "HorseIR/Tree/Expressions/Literals/FunctionLiteral.h"

#include "HorseIR/Tree/Types/Type.h"
#include "HorseIR/Tree/Types/WildcardType.h"
#include "HorseIR/Tree/Types/BasicType.h"
#include "HorseIR/Tree/Types/ListType.h"
#include "HorseIR/Tree/Types/DictionaryType.h"
#include "HorseIR/Tree/Types/EnumerationType.h"
#include "HorseIR/Tree/Types/FunctionType.h"
#include "HorseIR/Tree/Types/TableType.h"
#include "HorseIR/Tree/Types/KeyedTableType.h"
